services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /opt/szilardshomelab/appdata/prowlarr/config:/config
    ports:
      - 9696:9696
    networks:
      - ${DOCKER_NETWORK_NAME}
    restart: unless-stopped

networks:
  ${DOCKER_NETWORK_NAME}:
    driver: bridge
    external: true