services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /opt/szilardshomelab/appdata/radarr/config:/config
      - /${SMB}:/data
    ports:
      - 7878:7878
    networks:
      - ${DOCKER_NETWORK_NAME}
    restart: unless-stopped

networks:
  ${DOCKER_NETWORK_NAME}:
    driver: bridge
    external: true