services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /opt/appdata/sonarr/config:/config
    ports:
      - 8989:8989
    networks:
      - ${DOCKER_NETWORK_NAME}
    restart: unless-stopped

networks:
  ${DOCKER_NETWORK_NAME}:
    driver: bridge
    external: true