services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - /opt/appdata/sonarr/config:/config
      - /${SMB}:/data
    ports:
      - 8989:8989
    networks:
      - __DOCKER_NETWORK_NAME__
    restart: unless-stopped

networks:
  __DOCKER_NETWORK_NAME__:
    driver: bridge
    external: true