services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=51234
    volumes:
      - /opt/appdata/qbittorrent/config:/config
      - /${SMB}/torrents:/data/torrents
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
      - 51234:51234
    networks:
      - __DOCKER_NETWORK_NAME__
    restart: unless-stopped

networks:
  __DOCKER_NETWORK_NAME__:
    driver: bridge
    external: true